# Generated by Django 3.2.6 on 2021-10-04 11:58

from django.db import migrations, models
import eshop_settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0002_rename_copyright_setting_copy_right'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=eshop_settings.models.upload_image_path),
        ),
    ]
