# Generated by Django 3.2.6 on 2021-08-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_about', '0003_rename_image_employee_person_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='descriptions',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
