# Generated by Django 3.2.6 on 2021-08-31 12:26

from django.db import migrations, models
import eshop_products.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_about', '0004_auto_20210831_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='person_image',
        ),
        migrations.AddField(
            model_name='about',
            name='person_image',
            field=models.ImageField(blank=True, null=True, upload_to=eshop_products.models.upload_image_path),
        ),
    ]
