# Generated by Django 3.2.6 on 2021-08-31 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_about', '0005_auto_20210831_1656'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.RemoveField(
            model_name='about',
            name='person_image',
        ),
    ]
