# Generated by Django 3.2.6 on 2021-08-22 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_contact', '0002_send'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Send',
            new_name='ContactUs',
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
