# Generated by Django 3.2.6 on 2021-08-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_contact', '0004_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discription',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
